[supervisord]
 nodaemon=true

[program:nginx]
 command=/usr/sbin/nginx -g 'daemon off;'
 autostart=true
 autorestart=true

[program:fras]
 command=uvicorn main:app --host 0.0.0.0 --port 7860
 directory=/var/www/fras
 autostart=true
 autorestart=true

[program:portfolio]
 command=serve -s /var/www/portfolio -l 3000
 autostart=true
 autorestart=true